// Pure expertise data + composer — safe to import anywhere.
// The optional Claude API call lives at the bottom behind a dynamic import so
// no server secret or SDK code ever reaches the client bundle.

/**
 * AI reply drafting + sales coaching expertise.
 *
 * Two engines:
 *  1. Built-in expertise engine — freight-forwarding playbooks and reply
 *     composition that work offline, free, deterministic.
 *  2. Optional Claude upgrade — when ANTHROPIC_API_KEY is configured, drafts
 *     are generated by Claude with the built-in guidance as grounding.
 * Either way: drafts only. A human always reviews before sending.
 */

// ---------------------------------------------------------------------------
// Intent detection
// ---------------------------------------------------------------------------

export type Intent =
  | "RATE_INQUIRY" | "SHIPMENT_STATUS" | "CUSTOMS" | "CLOSING_DATE" | "DOCUMENTS"
  | "COMPLAINT" | "DELAY" | "NEW_LEAD" | "PAYMENT" | "TRANSLOADING" | "GENERAL";

const INTENT_RULES: { intent: Intent; words: string[] }[] = [
  { intent: "COMPLAINT", words: ["complaint", "disappointed", "unacceptable", "angry", "poor service", "not happy", "frustrated", "terrible", "worst"] },
  { intent: "CUSTOMS", words: ["customs", "hs code", "k1", "k2", "k3", "k8", "zb", "duty", "tax", "permit", "kastam", "declaration", "clearance", "sirim", "maqis"] },
  { intent: "CLOSING_DATE", words: ["closing", "cut off", "cut-off", "cutoff", "closing date", "si cut", "vgm"] },
  { intent: "RATE_INQUIRY", words: ["rate", "quotation", "quote", "price", "pricing", "how much", "charges", "cost", "freight rate", "offer"] },
  { intent: "TRANSLOADING", words: ["transload", "trans-load", "cross dock", "crossdock", "reload"] },
  { intent: "DELAY", words: ["delay", "delayed", "postpone", "rolled", "roll over", "late arrival", "congestion", "eta change"] },
  { intent: "SHIPMENT_STATUS", words: ["status", "where is", "eta", "etd", "arrived", "tracking", "container", "vessel", "update on", "when will"] },
  { intent: "DOCUMENTS", words: ["document", "bl ", "bill of lading", "invoice copy", "packing list", "form e", "form d", "coo", "certificate", "delivery order", "d/o", "release the do", "collect the do"] },
  { intent: "PAYMENT", words: ["payment", "outstanding", "overdue", "credit", "invoice due", "statement", "soa"] },
  { intent: "NEW_LEAD", words: ["new shipment", "inquiry", "enquiry", "interested", "first time", "can you handle", "do you provide", "need shipping", "import from", "export to"] },
];

export function detectIntent(message: string): Intent {
  const m = ` ${message.toLowerCase()} `;
  for (const rule of INTENT_RULES) {
    if (rule.words.some((w) => m.includes(w))) return rule.intent;
  }
  return "GENERAL";
}

export const INTENT_LABELS: Record<Intent, string> = {
  RATE_INQUIRY: "💵 Rate / quotation inquiry", SHIPMENT_STATUS: "🚢 Shipment status", CUSTOMS: "🛃 Customs inquiry",
  CLOSING_DATE: "⏰ Closing date", DOCUMENTS: "📄 Documents", COMPLAINT: "😟 Complaint", DELAY: "⏳ Delay",
  NEW_LEAD: "✨ New lead", PAYMENT: "💳 Payment / collection", TRANSLOADING: "🔄 Transloading", GENERAL: "💬 General",
};

// ---------------------------------------------------------------------------
// Built-in reply composer (deterministic fallback)
// ---------------------------------------------------------------------------

export type Tone = "PROFESSIONAL" | "FRIENDLY" | "APOLOGETIC";

const SIGN_OFF = "\n\nBest regards,\n{yourName}\nSolid Xpress M Sdn Bhd";

const REPLY_BODIES: Record<Intent, string> = {
  RATE_INQUIRY: "Thank you for your inquiry. To prepare an accurate quotation, kindly confirm:\n• Shipment mode (sea / air / land)\n• POL and POD\n• Commodity and HS code if known\n• Volume / weight / container type\n• Cargo ready date\n• Incoterm (EXW / FOB / CIF...)\n\nOnce we have these details, our team will revert with our best rate within one working day.",
  SHIPMENT_STATUS: "Thank you for checking with us. The latest status of your shipment {jobNo} is: {status}.\nCurrent ETA/ETD: {etaEtd}.\nNext step: {nextStep}.\n\nWe are monitoring the shipment closely and will update you proactively if anything changes.",
  CUSTOMS: "Thank you for your inquiry. We are checking the customs requirement for {commodity / jobNo} with our forwarding & declaration team — including the HS code, permit requirement and duty/tax treatment.\n\nWe will update you with a clear answer by {time}. If the shipment is urgent, please let us know so we can prioritise it.",
  CLOSING_DATE: "Kindly note that the closing date for {vessel / jobNo} is {closingDate}.\n\nTo avoid missing the vessel, please provide the pending documents/cargo by {deadline}. We will monitor the cut-off closely from our side and alert you of any change.",
  DOCUMENTS: "Thank you for your message. Regarding the documents for {jobNo}:\n{documentStatus}\n\nPlease let us know if you need any additional copies or amendments — we will arrange them promptly.",
  COMPLAINT: "Thank you for bringing this to our attention, and we sincerely apologise for the inconvenience caused.\n\nWe take this seriously. Here is what we are doing:\n1. We are investigating {issue} immediately.\n2. {ownerName} will personally follow up and update you by {time}.\n3. We will put a preventive step in place so this does not recur.\n\nThank you for your patience — we value your support and will make this right.",
  DELAY: "We would like to update you that {jobNo} is affected by {cause}. The revised timeline is {newTimeline}.\n\nThis is beyond our control, but we are actively monitoring and pushing for the earliest possible resolution. We will keep you updated at every change. We apologise for the inconvenience and appreciate your understanding.",
  NEW_LEAD: "Thank you for reaching out to Solid Xpress! We would be glad to assist with your shipment.\n\nTo advise the best solution and rate, kindly share:\n• Shipment mode (sea / air / land)\n• POL and POD\n• Commodity\n• Volume / weight\n• Cargo ready date\n• Any permit concern\n\nOur team will review and come back to you within one working day with a tailored proposal.",
  PAYMENT: "Gentle reminder regarding invoice {invoiceNo} ({amount}) which is due on {dueDate}.\n\nKindly arrange payment at your convenience, or let us know if the payment has already been made so we can update our records. If there is any issue with the invoice, please contact us and we will resolve it quickly.",
  TRANSLOADING: "Thank you for your instruction on the transloading shipment {jobNo}.\n\nCurrent status: {status}. Warehouse/transport coordination: {coordination}. We will send you photo/document proof once completed and keep you updated on timing at each step.",
  GENERAL: "Thank you for your message. We have noted your request regarding {topic} and our team is looking into it.\n\nWe will update you by {time}. Please let us know if there is anything urgent in the meantime.",
};

const TONE_OPENERS: Record<Tone, string> = {
  PROFESSIONAL: "Dear {customerName},\n\n",
  FRIENDLY: "Hi {customerName},\n\nHope you're doing well! ",
  APOLOGETIC: "Dear {customerName},\n\nFirst of all, we sincerely apologise for the trouble. ",
};

/** Deterministic reply draft (no API needed). {placeholders} stay visible so nothing false is sent. */
export function composeReply(message: string, tone: Tone = "PROFESSIONAL"): { intent: Intent; draft: string; tips: string[] } {
  const intent = detectIntent(message);
  const draft = TONE_OPENERS[tone] + REPLY_BODIES[intent] + SIGN_OFF;
  const tips = REPLY_TIPS[intent] ?? [];
  return { intent, draft, tips };
}

const REPLY_TIPS: Record<Intent, string[]> = {
  RATE_INQUIRY: ["Never quote a rate without confirming volume, commodity and validity — wrong quotes cause losses.", "Log this as a NEW_LEAD_INQUIRY job record and hand over to Sales if commercial follow-up is needed."],
  SHIPMENT_STATUS: ["Update proactively — the KPI counts proactive updates, not replies after the customer chases.", "Check the actual milestone before replying; never guess an ETA."],
  CUSTOMS: ["Escalate to the Forwarding team immediately (use the Internal Forwarding template) — don't guess HS codes or duty amounts.", "Never promise clearance times or duty figures that aren't confirmed."],
  CLOSING_DATE: ["Alert Operations at the same time — closing misses are a -100 💎 deduction if caused by follow-up failure.", "Give the customer a document deadline earlier than the real cut-off (buffer)."],
  DOCUMENTS: ["Double-check document names/numbers before sending — document mistakes are deductible errors.", "Record the handover in your job records."],
  COMPLAINT: ["Reply within 1 working hour, even if just to acknowledge.", "Never argue or blame in writing. Investigate first, then respond with facts.", "Escalate to your department head — complaints caused by negligence affect KPI."],
  DELAY: ["External delays (vessel, port, customs inspection, weather) don't deduct diamonds IF you update the customer properly — so update now.", "Give a specific next update time and keep it."],
  NEW_LEAD: ["Record the lead now (NEW_LEAD_INQUIRY job type) — unrecorded leads are a -20 💎 deduction.", "A converted lead with sales support earns +150 💎."],
  PAYMENT: ["Keep the tone friendly on the first reminder — most late payments are oversights.", "Loop in Finance so collection status is tracked."],
  TRANSLOADING: ["Confirm the customer's instruction in writing before moving cargo.", "Photo proof at each step protects everyone."],
  GENERAL: ["Give a specific time you'll come back to them — and beat it."],
};

// ---------------------------------------------------------------------------
// Sales coaching playbooks (follow-up & closing expertise)
// ---------------------------------------------------------------------------

export interface Playbook {
  key: string;
  title: string;
  when: string;
  steps: string[];
  script: string; // copy-paste message with {placeholders}
  expertTips: string[];
}

export const SALES_PLAYBOOKS: Playbook[] = [
  {
    key: "NEW_INQUIRY_FOLLOWUP",
    title: "🆕 New inquiry — first follow-up",
    when: "A prospect asked for rates/info and you replied. No response for 2–3 days.",
    steps: [
      "Day 0: send the quote + confirm you understood the requirement.",
      "Day 2–3: value follow-up (this script) — add something useful, don't just 'check in'.",
      "Day 7: share a relevant success story (similar customer/lane you handled well).",
      "Day 14: final nudge with an easy next step, then park in CRM with a review date.",
    ],
    script: "Hi {customerName}, following up on the {lane} quotation we sent on {date}. One thing I wanted to add — for {commodity} on this lane we can also {valueAdd, e.g. arrange customs clearance + delivery as one package}, which usually saves our clients time and cost. Is your shipment date confirmed yet? If your schedule changed, let me know and I'll re-check the best option for the new timing.",
    expertTips: [
      "Follow up with VALUE, not pressure — give new info each touch (rate trend, space situation, permit tip).",
      "Ask about their timeline, not 'any update?' — timeline questions get answers.",
      "Log every follow-up in CRM — 'quotation not followed up' is a -20 💎 deduction.",
    ],
  },
  {
    key: "QUOTE_NO_REPLY",
    title: "🤫 Quote sent, gone quiet",
    when: "Quotation delivered, several follow-ups, prospect went silent.",
    steps: [
      "Check internally first: was the rate competitive? Ask your manager for market feedback.",
      "Send the 'permission to close' script — it politely forces a decision.",
      "If no reply in 5 days, update CRM with lost reason 'no response' and set a 60-day revisit.",
    ],
    script: "Hi {customerName}, I don't want to keep disturbing you if the timing isn't right. May I check — is this shipment still going ahead? If you've chosen another provider or the plan changed, totally fine, just let me know and I'll close the file. And if you're still comparing, tell me what matters most (price / transit time / clearance support) and I'll see what we can do.",
    expertTips: [
      "The 'permission to close' message gets replies because it's easy to answer honestly.",
      "Silence usually means price or postponed shipment — offering the comparison question surfaces the real objection.",
      "Update the lost-deal reason — 'lost reason not updated' is a -10 💎 deduction and the data helps the whole team.",
    ],
  },
  {
    key: "PRICE_OBJECTION",
    title: "💰 'Your price is too high'",
    when: "Prospect says a competitor is cheaper.",
    steps: [
      "Thank them — an objection means they're still interested.",
      "Ask what the competitor's price INCLUDES (many quotes exclude DO fees, customs, delivery).",
      "Reframe on total cost + risk: clearance reliability, penalty avoidance, one-contact service.",
      "If still stuck, offer a scope adjustment (not just a discount): different service level, volume commitment.",
    ],
    script: "Thanks for being upfront, {customerName}. May I ask — does that price include {commonExclusions, e.g. DO fee, customs clearance, delivery to door}? Many quotes look cheaper but exclude these, and the total lands higher. With us the price covers {inclusions}, and you deal with one team for shipment + customs — if anything goes wrong we settle it, no finger-pointing. If your volume is regular, I can also check a committed rate for you. Can we compare the two quotes line by line?",
    expertTips: [
      "Never drop price immediately — it signals the first quote was inflated.",
      "'Compare line by line' wins deals: hidden charges are the #1 forwarder complaint.",
      "A wrong selling price causing loss is a -100 to -300 💎 deduction — check costs with Finance before any special rate.",
    ],
  },
  {
    key: "CLOSING_DEAL",
    title: "🤝 Closing the deal",
    when: "Prospect is satisfied with the quote but hasn't committed.",
    steps: [
      "Summarise what's agreed (lane, rate, scope) so there's nothing new to decide.",
      "Create gentle urgency that is TRUE (rate validity, space situation, closing dates).",
      "Ask a small-step close: 'shall we proceed with this shipment first?' not 'sign a contract'.",
      "Once agreed: confirm in writing, open the job, and do a complete handover to CS/Ops (+quality handover protects your commission).",
    ],
    script: "Hi {customerName}, to summarise: {lane}, {rate} all-in including {scope}, transit {days} days. Two things to note — this rate is valid until {validity}, and space for {month} is getting tight on this lane. If you're comfortable, shall we proceed with your {readyDate} shipment first? You can evaluate our service on this one before committing anything bigger. I'll handle the setup personally.",
    expertTips: [
      "'Try us on one shipment' removes the risk from saying yes — easiest close in freight.",
      "Only use REAL urgency (actual validity/space) — fake urgency destroys trust permanently.",
      "Commission is paid on COLLECTED GP: confirm credit terms up front and support Finance's collection follow-up.",
    ],
  },
  {
    key: "WIN_BACK",
    title: "🔁 Win back a lost/inactive customer",
    when: "A customer who used to ship with us hasn't booked in 2–3 months.",
    steps: [
      "Check history first: why did they go quiet? (complaint? price? volume drop?)",
      "If there was a service issue — acknowledge it head-on; don't pretend it didn't happen.",
      "Lead with what's changed/improved, then a concrete offer on their usual lane.",
    ],
    script: "Hi {customerName}, it's been a while since your last shipment with us and I wanted to check in personally. {ifIssue: I know the {issue} on your last shipment wasn't the experience you deserved — we've since {improvement}.} Rates on {theirUsualLane} have {marketUpdate}, and I'd love a chance to quote your next shipment. Do you have anything moving this month?",
    expertTips: [
      "Winning back an existing customer is 5× cheaper than finding a new one — check the inactive list monthly.",
      "Acknowledging a past issue rebuilds trust faster than avoiding it.",
      "Customer retention is 5% of your monthly score — win-backs move it directly.",
    ],
  },
  {
    key: "COLLECTION_SUPPORT",
    title: "💳 Payment collection support",
    when: "Finance flags an overdue invoice for your customer; your commission is held until collected.",
    steps: [
      "Call (don't just email) your contact — as the salesperson you have the relationship.",
      "Frame it as account housekeeping, not debt chasing.",
      "If there's a dispute, resolve it within 48h with Finance — disputes are the #1 collection blocker.",
      "Update Finance after every contact so the collection status is current.",
    ],
    script: "Hi {customerName}, quick housekeeping item — our finance team shows invoice {invoiceNo} ({amount}) from {date} still open. Could you help check if it's in your payment run? If there's any issue with the invoice (wrong PO, missing docs), tell me and I'll fix it today. Thanks so much — appreciate the smooth cooperation as always.",
    expertTips: [
      "Your commission is released only when GP is COLLECTED — collection support is paid work.",
      "'Payment issue not supported' is a -30 💎 deduction; supporting collection also scores 10% of the sales KPI.",
      "Most late payments are process issues (missing PO/docs) — offering to fix removes the excuse.",
    ],
  },
];

// ---------------------------------------------------------------------------
// Optional Claude upgrade
// ---------------------------------------------------------------------------

export function claudeConfigured(): boolean {
  return !!process.env.ANTHROPIC_API_KEY;
}

/**
 * Draft with Claude when configured. Grounded by the built-in playbook rules;
 * instructed to never invent rates/dates and to keep {placeholders} for
 * unknown facts. Returns null when no API key is configured or the call fails
 * (caller falls back to the deterministic composer).
 */
export async function claudeDraft(kind: "CUSTOMER_REPLY" | "SALES_MESSAGE", userInput: string, context: string): Promise<string | null> {
  if (!claudeConfigured()) return null;
  try {
    const { default: Anthropic } = await import("@anthropic-ai/sdk");
    const client = new Anthropic();
    const response = await client.messages.create({
      model: "claude-opus-4-8",
      max_tokens: 16000,
      thinking: { type: "adaptive" },
      system: [
        "You draft professional messages for staff of Solid Xpress M Sdn Bhd, a Malaysian freight forwarder (sea/air/land freight, customs clearance K1/K2/K3/K8/ZB, haulage, transloading).",
        "Rules: NEVER invent rates, dates, duty amounts, clearance times or promises — use {placeholders} like {rate} or {date} for anything not stated in the input. Match Malaysian business English. Be warm, clear and concrete. End customer messages with a courteous sign-off from Solid Xpress. Output ONLY the draft message, no preamble or explanation.",
        kind === "SALES_MESSAGE" ? "This is a sales follow-up/closing message: add value, use honest urgency only, make the next step small and easy." : "This is a customer-service reply: acknowledge, state the concrete action being taken, give a specific update time placeholder.",
      ].join("\n"),
      messages: [{ role: "user", content: `${context}\n\n---\nDraft a reply to this:\n${userInput}` }],
    });
    const text = response.content.filter((b) => b.type === "text").map((b) => b.text).join("\n").trim();
    return text || null;
  } catch (e) {
    console.error("claudeDraft failed, falling back to built-in composer:", e);
    return null;
  }
}
