/** Job handling types per role, from the management spec. */
export const JOB_TYPES: Record<string, string[]> = {
  CS: [
    "EXISTING_CUSTOMER_SHIPMENT", "NEW_LEAD_INQUIRY", "CUSTOMS_INQUIRY_FOLLOWUP", "CLOSING_DATE_FOLLOWUP",
    "SHIPMENT_STATUS_UPDATE", "DOCUMENT_COLLECTION", "COMPLAINT_HANDLING", "TRANSLOADING_COORDINATION",
    "INTERNAL_HANDOVER", "INQUIRY_CONVERSION_SUPPORT",
  ],
  OPERATION: [
    "BOOKING_COORDINATION", "JOB_CREATION", "MILESTONE_UPDATE", "CLOSING_DATE_MONITORING",
    "ETA_ETD_MONITORING", "EXCEPTION_HANDLING", "CROSS_TEAM_COORDINATION", "TRANSLOADING_OPERATION",
  ],
  FORWARDING: [
    "K1_DECLARATION", "K2_DECLARATION", "K3_DECLARATION", "K8_DECLARATION", "ZB_DECLARATION",
    "HS_CODE_CHECKING", "DUTY_TAX_CHECKING", "PERMIT_SUBMISSION", "CUSTOMS_RELEASE_FOLLOWUP",
    "CUSTOMS_QUERY_RESPONSE", "DOCUMENT_CHECKING", "PORT_AUTHORITY_COORDINATION",
  ],
  OTHER: ["GENERAL_JOB"],
};

export const JOB_STATUSES = ["OPEN", "IN_PROGRESS", "COMPLETED", "CANCELLED", "EXCLUDED_FROM_KPI"] as const;

export const label = (s: string) => s.replace(/_/g, " ").toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase());
