import { prisma } from "./prisma";
import { awardPoints } from "./points";
import { logAudit } from "./audit";
import { notify } from "./notify";

/** Finer classifier stored on the onboarding-bonus PointsTransaction. */
export const ONBOARDING_SOURCE = "NEW_ONBOARDING";
export const ONBOARDING_REVERSAL_SOURCE = "NEW_ONBOARDING_REVERSAL";

export type OnboardingTiming = "ON_USER_CREATION" | "ON_ONBOARDING_COMPLETION" | "MANUAL_OWNER_APPROVAL";

export interface OnboardingSetting {
  enabled: boolean;
  amount: number;
  timing: OnboardingTiming;
}

const DEFAULTS: OnboardingSetting = { enabled: true, amount: 50, timing: "ON_USER_CREATION" };

/** Read the singleton onboarding-bonus config, creating it with defaults on first use. */
export async function getOnboardingSetting(): Promise<OnboardingSetting> {
  const row = await prisma.onboardingBonusSetting.upsert({
    where: { id: "singleton" },
    create: { id: "singleton", ...DEFAULTS },
    update: {},
  });
  return { enabled: row.enabled, amount: row.amount, timing: row.timing as OnboardingTiming };
}

/** Has this user already been issued the onboarding bonus? (dedupe guard) */
export async function hasOnboardingBonus(userId: string): Promise<boolean> {
  const existing = await prisma.pointsTransaction.findFirst({
    where: { userId, sourceType: ONBOARDING_SOURCE, amount: { gt: 0 } },
    select: { id: true },
  });
  return Boolean(existing);
}

export type OnboardingResult =
  | { ok: true; awarded: true; amount: number; balanceBefore: number; balanceAfter: number }
  | { ok: true; awarded: false; reason: "disabled" }
  | { ok: false; awarded: false; reason: "duplicate" | "not_found" };

/**
 * Award the New Staff Onboarding Bonus (welcome "diamonds" = points) to a user.
 *
 * Reuses the existing points ledger, audit log and notification pipeline so the
 * grant is a real, auditable transaction — never a hidden balance write. Safe to
 * call more than once: the dedupe guard means a user can only ever receive it
 * once. Honours the enable/amount settings; the caller decides *when* to call
 * this (on account creation, manual approval, …) per the configured timing.
 */
export async function awardOnboardingDiamonds(userId: string, triggeredBy: string | null): Promise<OnboardingResult> {
  const setting = await getOnboardingSetting();
  if (!setting.enabled) return { ok: true, awarded: false, reason: "disabled" };

  if (await hasOnboardingBonus(userId)) return { ok: false, awarded: false, reason: "duplicate" };

  const user = await prisma.user.findUnique({ where: { id: userId }, select: { id: true, currentPoints: true } });
  if (!user) return { ok: false, awarded: false, reason: "not_found" };

  const balanceBefore = user.currentPoints;
  const amount = setting.amount;
  const balanceAfter = balanceBefore + amount;
  const generatedBy = triggeredBy ?? "SYSTEM";

  await prisma.$transaction(async (tx) => {
    // Ledger entry (recomputes the wallet aggregates authoritatively).
    await awardPoints(tx, {
      userId,
      amount,
      type: "BONUS",
      reason: "Welcome bonus for new staff onboarding.",
      sourceType: ONBOARDING_SOURCE,
      generatedBy,
      internalNote: "Auto-generated by onboarding bonus rule.",
      status: "APPROVED",
    });

    await logAudit(tx, {
      action: "ONBOARDING_DIAMOND_BONUS_AWARDED",
      entityId: userId,
      performedBy: generatedBy,
      oldValue: { diamondBalance: balanceBefore },
      newValue: { diamondBalance: balanceAfter, awarded: amount },
    });

    await notify(tx, {
      userId,
      type: "REWARD_APPROVED",
      title: "Welcome to Solid Xpress Team OS",
      body: `You received ${amount} welcome diamonds for completing your new staff onboarding. Start earning more diamonds through KPI, badges, missions and teamwork.`,
      link: "/wallet",
    });
  });

  return { ok: true, awarded: true, amount, balanceBefore, balanceAfter };
}

/**
 * Reverse a wrongly-issued onboarding bonus (Owner only). Posts a compensating
 * negative ledger entry so the balance history stays honest, and audits it.
 */
export async function reverseOnboardingDiamonds(userId: string, triggeredBy: string): Promise<{ ok: boolean; reason?: string }> {
  const grant = await prisma.pointsTransaction.findFirst({
    where: { userId, sourceType: ONBOARDING_SOURCE, amount: { gt: 0 } },
    orderBy: { createdAt: "desc" },
  });
  if (!grant) return { ok: false, reason: "no_bonus" };

  const already = await prisma.pointsTransaction.findFirst({ where: { userId, sourceType: ONBOARDING_REVERSAL_SOURCE } });
  if (already) return { ok: false, reason: "already_reversed" };

  const user = await prisma.user.findUnique({ where: { id: userId }, select: { currentPoints: true } });
  const balanceBefore = user?.currentPoints ?? 0;

  await prisma.$transaction(async (tx) => {
    await awardPoints(tx, {
      userId,
      amount: -grant.amount,
      type: "BONUS",
      reason: "Reversal of onboarding welcome bonus (issued in error).",
      sourceType: ONBOARDING_REVERSAL_SOURCE,
      generatedBy: triggeredBy,
      internalNote: "Manual reversal by owner.",
      status: "REVERSED",
    });
    await logAudit(tx, {
      action: "ONBOARDING_DIAMOND_BONUS_REVERSED",
      entityId: userId,
      performedBy: triggeredBy,
      oldValue: { diamondBalance: balanceBefore },
      newValue: { diamondBalance: balanceBefore - grant.amount },
    });
  });

  return { ok: true };
}
